"""initial

Revision ID: 9b2d3f5b9392
Revises: 
Create Date: 2025-12-29 09:43:07.378668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b2d3f5b9392'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute('CREATE EXTENSION IF NOT EXISTS pgcrypto;')

    op.create_table('admin_users',
    sa.Column(
        'id',
        sa.UUID(),
        server_default=sa.text('gen_random_uuid()'),
        nullable=False
    ),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('companies',
    sa.Column(
        'id',
        sa.UUID(),
        server_default=sa.text('gen_random_uuid()'),
        nullable=False
    ),    
    sa.Column('vergi_no', sa.String(length=10), nullable=False),
    sa.Column('company_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('status_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_code'),
    sa.UniqueConstraint('vergi_no')
    )
    op.create_table('modules',
    sa.Column(
        'id',
        sa.UUID(),
        server_default=sa.text('gen_random_uuid()'),
        nullable=False
    ),    
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('system_logs',
    sa.Column(
        'id',
        sa.UUID(),
        server_default=sa.text('gen_random_uuid()'),
        nullable=False
    ),    
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=True),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_modules',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'module_id')
    )
    op.create_table('licenses',
    sa.Column(
        'id',
        sa.UUID(),
        server_default=sa.text('gen_random_uuid()'),
        nullable=False
    ),    
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'module_id', name='uq_company_module_license')
    )
    op.create_table('tenant_dbs',
    sa.Column(
        'id',
        sa.UUID(),
        server_default=sa.text('gen_random_uuid()'),
        nullable=False
    ),    
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('db_name', sa.String(), nullable=False),
    sa.Column('db_user', sa.String(), nullable=False),
    sa.Column('db_password', sa.String(), nullable=False),
    sa.Column('ssl_mode', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenant_dbs')
    op.drop_table('licenses')
    op.drop_table('company_modules')
    op.drop_table('system_logs')
    op.drop_table('modules')
    op.drop_table('companies')
    op.drop_table('admin_users')
    # ### end Alembic commands ###

